

#pragma once

#include "Engine.h"

#define EVENT() GEngine->AddOnScreenDebugMessage(-1, 0.1f, FColor::Red, "Event!!");

enum MouseStates { FREE, DRAGGINGWINDOW, CLICKINGENVIRONMENT, CLICKINGBUTTON, CLICKINGMONSTER, ROTATINGCAMERA, HOVERINGBUTTON, USED };

enum ItemIndex { NOTHING, COIN, WOOD, POTION };

enum QuestTypeIndex { NOQUEST, KILLQUEST, COLLECTQUEST, SPECIALQUEST, GOTOQUEST };

enum MonsterIndex { NOMONSTER, FORESTSPRITE, FORESTELDER, TAINTEDSPRITE, GOLEM };

enum QuestStates { NOTTAKEN, INPROGRESS, CANCOMPLETE, COMPLETED, LOCKED };

enum WindowTypes { TRUEWINDOW, BOXWINDOW, NOWINDOW };